//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class About {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal About() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.About", typeof(About).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI Membership Charter.
        /// </summary>
        public static string ByLAWS {
            get {
                return ResourceManager.GetString("ByLAWS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAREER.
        /// </summary>
        public static string Career {
            get {
                return ResourceManager.GetString("Career", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENT ROLE.
        /// </summary>
        public static string CurrentRole {
            get {
                return ResourceManager.GetString("CurrentRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;div&gt;
        ///                    LOGI’s objective is to develop a network of Lebanese experts in the global energy industry and provide them with a platform to lobby Lebanese policy makers and educate Lebanese citizens on the key decisions facing the oil and gas industry.
        ///                &lt;/div&gt;
        ///                &lt;br /&gt;
        ///                &lt;div&gt;It focuses on public awareness, policy development and advocacy to help Lebanon maximize the economic and social benefits of its oil and gas wealth – and avoid the resource cu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string DescriptionDiv {
            get {
                return ResourceManager.GetString("DescriptionDiv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD WHITEPAPER.
        /// </summary>
        public static string DownloadPaper {
            get {
                return ResourceManager.GetString("DownloadPaper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD PDF REPORT.
        /// </summary>
        public static string DownloadPdfReport {
            get {
                return ResourceManager.GetString("DownloadPdfReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD OUR.
        /// </summary>
        public static string DownloadReport1 {
            get {
                return ResourceManager.GetString("DownloadReport1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REPORT.
        /// </summary>
        public static string DownloadReport2 {
            get {
                return ResourceManager.GetString("DownloadReport2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDUCATE.
        /// </summary>
        public static string Educate {
            get {
                return ResourceManager.GetString("Educate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educating policymakers and citizens on oil and gas.
        /// </summary>
        public static string EducateDesc {
            get {
                return ResourceManager.GetString("EducateDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EDUCATION.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ENABLE EXPERTS.
        /// </summary>
        public static string Enable {
            get {
                return ResourceManager.GetString("Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platform for experts to shape Lebanon’s oil and gas industry.
        /// </summary>
        public static string EnableDesc {
            get {
                return ResourceManager.GetString("EnableDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPENSES.
        /// </summary>
        public static string Expenses {
            get {
                return ResourceManager.GetString("Expenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERTISE.
        /// </summary>
        public static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FINANCIALS.
        /// </summary>
        public static string Financial {
            get {
                return ResourceManager.GetString("Financial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI is the first Lebanese organization to join the PWYP network and the WRI Access Intiative..
        /// </summary>
        public static string FirstLebanese {
            get {
                return ResourceManager.GetString("FirstLebanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FUNDING.
        /// </summary>
        public static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gift Acceptance Policy.
        /// </summary>
        public static string GiftAcceptance {
            get {
                return ResourceManager.GetString("GiftAcceptance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INFLUENCE.
        /// </summary>
        public static string Influence {
            get {
                return ResourceManager.GetString("Influence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advancing innovative policy solutions.
        /// </summary>
        public static string InfluenceDesc {
            get {
                return ResourceManager.GetString("InfluenceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about LOGI&apos;s vision.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI&apos;s heart.
        /// </summary>
        public static string LogisHeart {
            get {
                return ResourceManager.GetString("LogisHeart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our ADVISORY BOARD.
        /// </summary>
        public static string MeetAdvisory {
            get {
                return ResourceManager.GetString("MeetAdvisory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our CO-FOUNDERS.
        /// </summary>
        public static string MeetCos {
            get {
                return ResourceManager.GetString("MeetCos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meet our TEAM.
        /// </summary>
        public static string MeetTeam {
            get {
                return ResourceManager.GetString("MeetTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEMBERS.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help Lebanon Maximize The Economic and Social Benefits of its Oil and Gas Wealth.
        /// </summary>
        public static string MessionDescription {
            get {
                return ResourceManager.GetString("MessionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MISSION.
        /// </summary>
        public static string Mission {
            get {
                return ResourceManager.GetString("Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFFICIAL DOCUMENTS.
        /// </summary>
        public static string OfficialDocs {
            get {
                return ResourceManager.GetString("OfficialDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About LOGI.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI&apos;s PARTNERS.
        /// </summary>
        public static string Partners {
            get {
                return ResourceManager.GetString("Partners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous reports:.
        /// </summary>
        public static string PrevReports {
            get {
                return ResourceManager.GetString("PrevReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI is a member of PWYP; a global coalition of more than 800 civil society organizations united in their call for an open and accountable extractive sector..
        /// </summary>
        public static string PublisWhatYouPay {
            get {
                return ResourceManager.GetString("PublisWhatYouPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string Purpose {
            get {
                return ResourceManager.GetString("Purpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI &lt;br /&gt; is an independent NGO aiming to develop a network of Lebanese Oil and Gas Experts.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGISTRATION DOCUMENTS.
        /// </summary>
        public static string RegistrationDocs {
            get {
                return ResourceManager.GetString("RegistrationDocs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI is a member of The Access Initiative (TAI), the world’s largest network of civil society organizations ensuring that citizens have the right and ability to influence decisions about their natural resources..
        /// </summary>
        public static string TheAccessIntiative {
            get {
                return ResourceManager.GetString("TheAccessIntiative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRANSPARENCY: We practice what we preach!.
        /// </summary>
        public static string Transparency {
            get {
                return ResourceManager.GetString("Transparency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI aims to advocate for transparency in Lebanon’s oil and gas industry, and will thus be fully transparent in its own operations. LOGI’s financial and administrative activities will be made available to the wider public in an annual report..
        /// </summary>
        public static string TransparencyDesc {
            get {
                return ResourceManager.GetString("TransparencyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VISION.
        /// </summary>
        public static string Vision {
            get {
                return ResourceManager.GetString("Vision", resourceCulture);
            }
        }
    }
}
