//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Basics {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Basics() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.Basics", typeof(Basics).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a lot needs to be done.
        /// </summary>
        public static string ALotNeed {
            get {
                return ResourceManager.GetString("ALotNeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string And {
            get {
                return ResourceManager.GetString("And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and oh by the way, it might take 4 to 6 years!.
        /// </summary>
        public static string AndOh {
            get {
                return ResourceManager.GetString("AndOh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to And Then?.
        /// </summary>
        public static string AndThen {
            get {
                return ResourceManager.GetString("AndThen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appraisal.
        /// </summary>
        public static string Appraisal {
            get {
                return ResourceManager.GetString("Appraisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about Oil and Gas in Lebanon.
        /// </summary>
        public static string BasicsDes {
            get {
                return ResourceManager.GetString("BasicsDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string BasicsTitle {
            get {
                return ResourceManager.GetString("BasicsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to because.
        /// </summary>
        public static string Because {
            get {
                return ResourceManager.GetString("Because", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculate approx. years.
        /// </summary>
        public static string Calculate {
            get {
                return ResourceManager.GetString("Calculate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commercially &lt;br/&gt; extracted.
        /// </summary>
        public static string Commercially {
            get {
                return ResourceManager.GetString("Commercially", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Construction of the well.
        /// </summary>
        public static string Construction {
            get {
                return ResourceManager.GetString("Construction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decommissioning.
        /// </summary>
        public static string Decommissioning {
            get {
                return ResourceManager.GetString("Decommissioning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decrees.
        /// </summary>
        public static string Degrees {
            get {
                return ResourceManager.GetString("Degrees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development.
        /// </summary>
        public static string Development {
            get {
                return ResourceManager.GetString("Development", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Development drilling.
        /// </summary>
        public static string DevelopmentDrilling {
            get {
                return ResourceManager.GetString("DevelopmentDrilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN DRILLING &amp; EXPLORATION STARTS.
        /// </summary>
        public static string DrillingExploration {
            get {
                return ResourceManager.GetString("DrillingExploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration unknown - dependent on political will.
        /// </summary>
        public static string DurationUnkownPolitical {
            get {
                return ResourceManager.GetString("DurationUnkownPolitical", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESTABLISHING.
        /// </summary>
        public static string Estaplish {
            get {
                return ResourceManager.GetString("Estaplish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploration.
        /// </summary>
        public static string Exploration {
            get {
                return ResourceManager.GetString("Exploration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 to 6 years.
        /// </summary>
        public static string FourYears {
            get {
                return ResourceManager.GetString("FourYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from our Oil and gas wealth?.
        /// </summary>
        public static string FromOurOilAnd {
            get {
                return ResourceManager.GetString("FromOurOilAnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Government action is needed.
        /// </summary>
        public static string GovernmentAction {
            get {
                return ResourceManager.GetString("GovernmentAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hopefully,&lt;br/&gt;OIL or GAS is discovered..
        /// </summary>
        public static string Hopefully {
            get {
                return ResourceManager.GetString("Hopefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In conclusion, it will take at least 7 years to start producing oil and gas, assuming the required decrees are passed today..
        /// </summary>
        public static string InConclusion {
            get {
                return ResourceManager.GetString("InConclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to by Council of Ministers.
        /// </summary>
        public static string InCouncilof {
            get {
                return ResourceManager.GetString("InCouncilof", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in proven oil and gas production areas.
        /// </summary>
        public static string InProven {
            get {
                return ResourceManager.GetString("InProven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INTERNATIONAL COMPANIES BID &lt;br/&gt;AND ARE SELECTED!.
        /// </summary>
        public static string InternationalComp {
            get {
                return ResourceManager.GetString("InternationalComp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        public static string Licensing {
            get {
                return ResourceManager.GetString("Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to more than.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to needs to be passed by Parliament.
        /// </summary>
        public static string NeedsPar {
            get {
                return ResourceManager.GetString("NeedsPar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to need to be passed.
        /// </summary>
        public static string NeedToBePassed {
            get {
                return ResourceManager.GetString("NeedToBePassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOT SO FAST!.
        /// </summary>
        public static string NotSoFar {
            get {
                return ResourceManager.GetString("NotSoFar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to offshore installations&lt;br/&gt;are decommissioned and dismantled.
        /// </summary>
        public static string OffshoreInstallation {
            get {
                return ResourceManager.GetString("OffshoreInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of its oil or gas could take 1 - 2 years.
        /// </summary>
        public static string OfOilAndGas {
            get {
                return ResourceManager.GetString("OfOilAndGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of the discovered reservoir and.
        /// </summary>
        public static string OfTheReserv {
            get {
                return ResourceManager.GetString("OfTheReserv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OIL or GAS.
        /// </summary>
        public static string OilOrGas {
            get {
                return ResourceManager.GetString("OilOrGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once oil and gas reservoirs are depleted&lt;br/&gt;and installations reach the end of their economic lives,.
        /// </summary>
        public static string OnceOilAndGas {
            get {
                return ResourceManager.GetString("OnceOilAndGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 3 years.
        /// </summary>
        public static string OneToThree {
            get {
                return ResourceManager.GetString("OneToThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 to 2 years.
        /// </summary>
        public static string OneToTwo {
            get {
                return ResourceManager.GetString("OneToTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to one year.
        /// </summary>
        public static string OneYear {
            get {
                return ResourceManager.GetString("OneYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please note that these company logos are displayed for illustrative purposes..
        /// </summary>
        public static string PleaseNote {
            get {
                return ResourceManager.GetString("PleaseNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREREQUISITES.
        /// </summary>
        public static string PREREQUISITES {
            get {
                return ResourceManager.GetString("PREREQUISITES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prerequisites.
        /// </summary>
        public static string Prerequisties {
            get {
                return ResourceManager.GetString("Prerequisties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production.
        /// </summary>
        public static string Production {
            get {
                return ResourceManager.GetString("Production", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does Lebanon have Oil and Gas?.
        /// </summary>
        public static string Question1 {
            get {
                return ResourceManager.GetString("Question1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How Much?.
        /// </summary>
        public static string Question2 {
            get {
                return ResourceManager.GetString("Question2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What has Lebanon done so far?.
        /// </summary>
        public static string Question3 {
            get {
                return ResourceManager.GetString("Question3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When are we going to benefit?.
        /// </summary>
        public static string Question4 {
            get {
                return ResourceManager.GetString("Question4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who makes the decisions?.
        /// </summary>
        public static string Question5 {
            get {
                return ResourceManager.GetString("Question5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What are our neighbors doing?.
        /// </summary>
        public static string Question6 {
            get {
                return ResourceManager.GetString("Question6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to read again.
        /// </summary>
        public static string ReadAgain {
            get {
                return ResourceManager.GetString("ReadAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rights are given to &lt;br/&gt; winning oil companies &lt;br/&gt;to explore &amp; extract hydrocarbons &lt;br/&gt;in selected areas.
        /// </summary>
        public static string RightsAreGiven {
            get {
                return ResourceManager.GetString("RightsAreGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to see.
        /// </summary>
        public static string See {
            get {
                return ResourceManager.GetString("See", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7 years.
        /// </summary>
        public static string SevenYears {
            get {
                return ResourceManager.GetString("SevenYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like this Page? Share it!.
        /// </summary>
        public static string ShareThisPage {
            get {
                return ResourceManager.GetString("ShareThisPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleum tax law.
        /// </summary>
        public static string TaxLaw {
            get {
                return ResourceManager.GetString("TaxLaw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 to 30 years.
        /// </summary>
        public static string TenToThirty {
            get {
                return ResourceManager.GetString("TenToThirty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the characteristics.
        /// </summary>
        public static string TheCharactaristics {
            get {
                return ResourceManager.GetString("TheCharactaristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decrees are issued by the Council of Ministers and are related to the blocks delineation, the model contract, and tender protocol..
        /// </summary>
        public static string TheDecrease {
            get {
                return ResourceManager.GetString("TheDecrease", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The journey will not start before.
        /// </summary>
        public static string TheJourney {
            get {
                return ResourceManager.GetString("TheJourney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the properties.
        /// </summary>
        public static string TheProperties {
            get {
                return ResourceManager.GetString("TheProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE QUESTION WE ALL CRAVE AN ANSWER FOR.
        /// </summary>
        public static string TheQuestion {
            get {
                return ResourceManager.GetString("TheQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to these laws are passed.
        /// </summary>
        public static string TheseLaws {
            get {
                return ResourceManager.GetString("TheseLaws", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to kickstart oil and gas exploration.
        /// </summary>
        public static string ToKickStart {
            get {
                return ResourceManager.GetString("ToKickStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to until first oil or gas
        ///commercially extracted.
        /// </summary>
        public static string UntilExtracted {
            get {
                return ResourceManager.GetString("UntilExtracted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Animated Overview of Lebanese Oil and Gas.
        /// </summary>
        public static string VideoDesc {
            get {
                return ResourceManager.GetString("VideoDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN ARE &lt;br/&gt; WE GOING TO &lt;br/&gt; BENEFIT?.
        /// </summary>
        public static string WhenAreWe {
            get {
                return ResourceManager.GetString("WhenAreWe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHEN ARE WE GOING TO BENEFIT?.
        /// </summary>
        public static string WhenToBenefit {
            get {
                return ResourceManager.GetString("WhenToBenefit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to but why wait this long?.
        /// </summary>
        public static string WhyWait {
            get {
                return ResourceManager.GetString("WhyWait", resourceCulture);
            }
        }
    }
}
