//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Donate {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Donate() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.Donate", typeof(Donate).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUPPORT LOGI to drive change in a country in urgent need..
        /// </summary>
        public static string Desc1 {
            get {
                return ResourceManager.GetString("Desc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join us in this challenging but exciting journey!.
        /// </summary>
        public static string Desc2 {
            get {
                return ResourceManager.GetString("Desc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DONATE.
        /// </summary>
        public static string DonateTitle {
            get {
                return ResourceManager.GetString("DonateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD PDF.
        /// </summary>
        public static string DownloadPDF {
            get {
                return ResourceManager.GetString("DownloadPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Amount.
        /// </summary>
        public static string EnterAmount {
            get {
                return ResourceManager.GetString("EnterAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GIFT ACCEPTANCE POLICY.
        /// </summary>
        public static string GiftPolicy {
            get {
                return ResourceManager.GetString("GiftPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LOGI&apos;s commitment to transparency, accountability and good governance means that we shall solicit and accept direct philanthropic support that is aligned with our mission, upholds our core values and maintains our reputation and independence.
        ///                &lt;br /&gt;
        ///                &lt;br /&gt;
        ///                If you encounter any difficulties in making a donation or for other queries, please contact us at.
        /// </summary>
        public static string GiftPolicyDesc {
            get {
                return ResourceManager.GetString("GiftPolicyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build the largest network of Lebanese oil and gas experts from around the World.
        /// </summary>
        public static string Help1 {
            get {
                return ResourceManager.GetString("Help1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Develop the most effective policy recommendations to help build Lebanon&apos;s petroleum sector.
        /// </summary>
        public static string Help2 {
            get {
                return ResourceManager.GetString("Help2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boost our campaigns to prevent corruption in Lebanon&apos;s petroleum sector.
        /// </summary>
        public static string Help3 {
            get {
                return ResourceManager.GetString("Help3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use the best technology and tools to be more effective campaigners.
        /// </summary>
        public static string Help4 {
            get {
                return ResourceManager.GetString("Help4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broaden our reach to all Lebanese citizens in and outside of Lebanon.
        /// </summary>
        public static string Help5 {
            get {
                return ResourceManager.GetString("Help5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your donation will help us to.
        /// </summary>
        public static string HelpTitle {
            get {
                return ResourceManager.GetString("HelpTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donate.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
    }
}
