//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Home {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Home() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.Home", typeof(Home).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask an oil and gas expert Download &lt;span style=&quot;color:#00a88f;&quot;&gt;LOGandLearn&lt;/span&gt; App.
        /// </summary>
        public static string AboutDesc1 {
            get {
                return ResourceManager.GetString("AboutDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get straight facts on Lebanon’s oil and gas, and check the validity of politicians&apos; statements..
        /// </summary>
        public static string AboutDesc2 {
            get {
                return ResourceManager.GetString("AboutDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This app is a project by the Samir Kassir Foundation, in partnership with Middle East
        ///                    Srategic Perspective and in cooperation with the Lebanese Oil &amp; Gas Initiative.
        /// </summary>
        public static string AboutDesc3 {
            get {
                return ResourceManager.GetString("AboutDesc3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about Lebanon&apos;s Oil and Gas.
        /// </summary>
        public static string AboutLOGI {
            get {
                return ResourceManager.GetString("AboutLOGI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basics.
        /// </summary>
        public static string Basics {
            get {
                return ResourceManager.GetString("Basics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get answers to your questions about Lebanese oil and gas.
        /// </summary>
        public static string BasicsDesc {
            get {
                return ResourceManager.GetString("BasicsDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about Oil and Gas in Lebanon.
        /// </summary>
        public static string BasicsDesc2 {
            get {
                return ResourceManager.GetString("BasicsDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explore our Database.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN LOGI.
        /// </summary>
        public static string JoinLogi {
            get {
                return ResourceManager.GetString("JoinLogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volunteer with LOGI or join as an expert.
        /// </summary>
        public static string JoinLogiDesc {
            get {
                return ResourceManager.GetString("JoinLogiDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Issues.
        /// </summary>
        public static string KeyIssues {
            get {
                return ResourceManager.GetString("KeyIssues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow major issues on oil and gas in Lebanon.
        /// </summary>
        public static string KeyIssuesDesc {
            get {
                return ResourceManager.GetString("KeyIssuesDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to driving Lebanon&apos;s oil and gas sector.
        /// </summary>
        public static string KeyIssuesDesc2 {
            get {
                return ResourceManager.GetString("KeyIssuesDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informing, Lobbying, Promoting Transparency.
        /// </summary>
        public static string LandingTitle {
            get {
                return ResourceManager.GetString("LandingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LEARN MORE.
        /// </summary>
        public static string LearnMore {
            get {
                return ResourceManager.GetString("LearnMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MORE ABOUT LOGI.
        /// </summary>
        public static string MoreAboutLogi {
            get {
                return ResourceManager.GetString("MoreAboutLogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than 500 documents, 55 media outlets, English, French, Arabic.
        /// </summary>
        public static string MoreThan {
            get {
                return ResourceManager.GetString("MoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The most extensive collection of articles and videos about Oil and Gas in Lebanon..
        /// </summary>
        public static string OilAndGas {
            get {
                return ResourceManager.GetString("OilAndGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Page.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Independent NGO Promoting the Transparent Management of Lebanon’s Oil and Gas Resources.
        /// </summary>
        public static string Quote {
            get {
                return ResourceManager.GetString("Quote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese Oil and Gas Initiative &lt;br /&gt;(LOGI) Introduction.
        /// </summary>
        public static string VideoOverlay {
            get {
                return ResourceManager.GetString("VideoOverlay", resourceCulture);
            }
        }
    }
}
