//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Join {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Join() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.Join", typeof(Join).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as an Expert.
        /// </summary>
        public static string ApplyExpertTitle {
            get {
                return ResourceManager.GetString("ApplyExpertTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY NOW.
        /// </summary>
        public static string ApplyNow {
            get {
                return ResourceManager.GetString("ApplyNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply To Job.
        /// </summary>
        public static string ApplyPageTitle {
            get {
                return ResourceManager.GetString("ApplyPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you an expert?.
        /// </summary>
        public static string AreYouExpert {
            get {
                return ResourceManager.GetString("AreYouExpert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EXPERTS ONLY &lt;br/&gt;
        ///NO POLITICAL AFFILIATIONS&lt;br/&gt;
        ///NO CONFLICT OF INTEREST&lt;br/&gt;
        ///VOLUNTEERS&lt;br/&gt;
        ///DRIVE TO MAKE A DIFFERENCE.
        /// </summary>
        public static string Conditions {
            get {
                return ResourceManager.GetString("Conditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conditions to Apply:.
        /// </summary>
        public static string ConditionsTitle {
            get {
                return ResourceManager.GetString("ConditionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country of Residence.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Openings.
        /// </summary>
        public static string CurrentOpenings {
            get {
                return ResourceManager.GetString("CurrentOpenings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline.
        /// </summary>
        public static string Deadline {
            get {
                return ResourceManager.GetString("Deadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired Characteristics.
        /// </summary>
        public static string DesiredChar {
            get {
                return ResourceManager.GetString("DesiredChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOWNLOAD PDF.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download PDF to learn more about LOGI’s rigorous selection process and policy.
        /// </summary>
        public static string DownloadDesc {
            get {
                return ResourceManager.GetString("DownloadDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Learn more about LOGI&apos;s rigorous selection process and policy.
        /// </summary>
        public static string DownloadDesc2 {
            get {
                return ResourceManager.GetString("DownloadDesc2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Education.
        /// </summary>
        public static string Education {
            get {
                return ResourceManager.GetString("Education", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essential Responsibilities.
        /// </summary>
        public static string EssentialRes {
            get {
                return ResourceManager.GetString("EssentialRes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APPLY NOW.
        /// </summary>
        public static string ExpertApply {
            get {
                return ResourceManager.GetString("ExpertApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join LOGI to shape Lebanon’s petroleum industry.
        /// </summary>
        public static string ExpertDesc1 {
            get {
                return ResourceManager.GetString("ExpertDesc1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expertise.
        /// </summary>
        public static string Expertise {
            get {
                return ResourceManager.GetString("Expertise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill out the form to apply.
        /// </summary>
        public static string FillForm {
            get {
                return ResourceManager.GetString("FillForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How do you envisage your contribution to LOGI?.
        /// </summary>
        public static string HowToContribute {
            get {
                return ResourceManager.GetString("HowToContribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job number.
        /// </summary>
        public static string JobNumber {
            get {
                return ResourceManager.GetString("JobNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join as an Expert.
        /// </summary>
        public static string JoinExperts {
            get {
                return ResourceManager.GetString("JoinExperts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Become a contributor by joining the Network of Oil &amp; Gas Experts.
        /// </summary>
        public static string JoinExpertsDes {
            get {
                return ResourceManager.GetString("JoinExpertsDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JOIN LOGI.
        /// </summary>
        public static string JoinLogi {
            get {
                return ResourceManager.GetString("JoinLogi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join the Team.
        /// </summary>
        public static string JoinTeam {
            get {
                return ResourceManager.GetString("JoinTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get hired and be part of the LOGI team.
        /// </summary>
        public static string JoinTeamDes {
            get {
                return ResourceManager.GetString("JoinTeamDes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your message goes here.
        /// </summary>
        public static string MessagePlaceholder {
            get {
                return ResourceManager.GetString("MessagePlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outcome.
        /// </summary>
        public static string Outcome {
            get {
                return ResourceManager.GetString("Outcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join LOGI.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Political affiliation.
        /// </summary>
        public static string PoliticalAffiliation {
            get {
                return ResourceManager.GetString("PoliticalAffiliation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolling Deadline.
        /// </summary>
        public static string ProjectDeadline {
            get {
                return ResourceManager.GetString("ProjectDeadline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read more and Apply.
        /// </summary>
        public static string ReadAndApply {
            get {
                return ResourceManager.GetString("ReadAndApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Summary.
        /// </summary>
        public static string RoleSummary {
            get {
                return ResourceManager.GetString("RoleSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary.
        /// </summary>
        public static string Salary {
            get {
                return ResourceManager.GetString("Salary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SEND.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for your &lt;br/&gt; application!&lt;br /&gt;
        ///                        &lt;span&gt;We will review it and get back to you.&lt;/span&gt;.
        /// </summary>
        public static string Thankyou {
            get {
                return ResourceManager.GetString("Thankyou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UPLOAD RESUME.
        /// </summary>
        public static string UploadResume {
            get {
                return ResourceManager.GetString("UploadResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Why do you want to join LOGI?.
        /// </summary>
        public static string WhyToJoin {
            get {
                return ResourceManager.GetString("WhyToJoin", resourceCulture);
            }
        }
    }
}
