//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOGI.App_LocalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Timeline {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Timeline() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LOGI.App_LocalResources.Timeline", typeof(Timeline).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all categories.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all countries.
        /// </summary>
        public static string AllCountries {
            get {
                return ResourceManager.GetString("AllCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bilateral Agreements.
        /// </summary>
        public static string BilateralAgreements {
            get {
                return ResourceManager.GetString("BilateralAgreements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environmental.
        /// </summary>
        public static string Environmental {
            get {
                return ResourceManager.GetString("Environmental", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exploratory Drilling.
        /// </summary>
        public static string ExploratoryDrilling {
            get {
                return ResourceManager.GetString("ExploratoryDrilling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter by.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to for Oil and Gas in Lebanon and the region.
        /// </summary>
        public static string ForOilAndGas {
            get {
                return ResourceManager.GetString("ForOilAndGas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FULL TIMELINE HERE.
        /// </summary>
        public static string FullTimeLine {
            get {
                return ResourceManager.GetString("FullTimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geophysical Surveying.
        /// </summary>
        public static string GeophysicalSurveying {
            get {
                return ResourceManager.GetString("GeophysicalSurveying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislation.
        /// </summary>
        public static string Legislation {
            get {
                return ResourceManager.GetString("Legislation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licensing.
        /// </summary>
        public static string Licensing {
            get {
                return ResourceManager.GetString("Licensing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maritime Boundary Dispute.
        /// </summary>
        public static string MaritimeBoundaryDispute {
            get {
                return ResourceManager.GetString("MaritimeBoundaryDispute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string Pagetitle {
            get {
                return ResourceManager.GetString("Pagetitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regional Discoveries.
        /// </summary>
        public static string RegionalDiscoveries {
            get {
                return ResourceManager.GetString("RegionalDiscoveries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of oil and gas developments in Lebanon and the region.
        /// </summary>
        public static string Subtitle {
            get {
                return ResourceManager.GetString("Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TIMELINE.
        /// </summary>
        public static string TimeLine {
            get {
                return ResourceManager.GetString("TimeLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeline.
        /// </summary>
        public static string TimelineTitle {
            get {
                return ResourceManager.GetString("TimelineTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jun 2015.
        /// </summary>
        public static string TL101 {
            get {
                return ResourceManager.GetString("TL101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2D Onshore Seismic Survey.
        /// </summary>
        public static string TL102 {
            get {
                return ResourceManager.GetString("TL102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Late 1960s.
        /// </summary>
        public static string TL11 {
            get {
                return ResourceManager.GetString("TL11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First O&amp;G Onshore Exploration.
        /// </summary>
        public static string TL12 {
            get {
                return ResourceManager.GetString("TL12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanese Petroleum Company Drills exploratory wells in al Qa, Adloun, and another in Yamour..
        /// </summary>
        public static string TL13 {
            get {
                return ResourceManager.GetString("TL13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Early 1970s.
        /// </summary>
        public static string TL21 {
            get {
                return ResourceManager.GetString("TL21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seismic Surveys Offshore Tripoli.
        /// </summary>
        public static string TL22 {
            get {
                return ResourceManager.GetString("TL22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan 2007.
        /// </summary>
        public static string TL31 {
            get {
                return ResourceManager.GetString("TL31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan 2007 Lebanon-Cyprus EEZ Agreement Signed.
        /// </summary>
        public static string TL32 {
            get {
                return ResourceManager.GetString("TL32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lebanon and Cyprus agree in principle to terms over demarcating their Exclusive Economic Zones. The Lebanese government has never ratified this agreement.
        /// </summary>
        public static string TL33 {
            get {
                return ResourceManager.GetString("TL33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jan 2009.
        /// </summary>
        public static string TL41 {
            get {
                return ResourceManager.GetString("TL41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel: Discovery of Tamer Gas Field.
        /// </summary>
        public static string TL42 {
            get {
                return ResourceManager.GetString("TL42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tamer Gas Field is a reservoir estimated to contain 10 trillion cubic feet of natural gas.
        /// </summary>
        public static string TL43 {
            get {
                return ResourceManager.GetString("TL43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aug 2010.
        /// </summary>
        public static string TL51 {
            get {
                return ResourceManager.GetString("TL51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hydrocarbon Law Passed.
        /// </summary>
        public static string TL52 {
            get {
                return ResourceManager.GetString("TL52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec 2010.
        /// </summary>
        public static string TL61 {
            get {
                return ResourceManager.GetString("TL61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Israel: Leviathan Gas Field Discovered.
        /// </summary>
        public static string TL62 {
            get {
                return ResourceManager.GetString("TL62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dec 2011.
        /// </summary>
        public static string TL71 {
            get {
                return ResourceManager.GetString("TL71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cyprus: Aphrodite Gas Field Discovered.
        /// </summary>
        public static string TL72 {
            get {
                return ResourceManager.GetString("TL72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In June 2015 Cyprus announces plans for the commercialization of this field..
        /// </summary>
        public static string TL73 {
            get {
                return ResourceManager.GetString("TL73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nov 2012.
        /// </summary>
        public static string TL81 {
            get {
                return ResourceManager.GetString("TL81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Petroleum Administration Formed.
        /// </summary>
        public static string TL82 {
            get {
                return ResourceManager.GetString("TL82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Board of Lebanese Petroleum Administration formed after months of debate and missed deadlines.
        /// </summary>
        public static string TL83 {
            get {
                return ResourceManager.GetString("TL83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feb 2013.
        /// </summary>
        public static string TL91 {
            get {
                return ResourceManager.GetString("TL91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-qualification Phase Launched.
        /// </summary>
        public static string TL92 {
            get {
                return ResourceManager.GetString("TL92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In March, the pre-qualification round closed with 46 companies eligible to bid in Lebanon’s first licensing round.
        /// </summary>
        public static string TL93 {
            get {
                return ResourceManager.GetString("TL93", resourceCulture);
            }
        }
    }
}
