// <auto-generated />
namespace LOGI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class not_Mandatory_SourceID_AuthorID : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(not_Mandatory_SourceID_AuthorID));
        
        string IMigrationMetadata.Id
        {
            get { return "201602131727038_not_Mandatory_SourceID_AuthorID"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
