// <auto-generated />
namespace LOGI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addarabictosomeentities : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addarabictosomeentities));
        
        string IMigrationMetadata.Id
        {
            get { return "201602131052127_Add-arabic-to-some-entities"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
