// <auto-generated />
namespace LOGI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addauthorentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addauthorentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201602130826536_Add-author-entity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
